### ISSUE TITLE
Re-format or don't show Twitch message when user joins Slack channel

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/twitch_slack_bot#3]
For example:
`On Slack, rhoegg said: <@U07E467PX|rhoegg> has joined the channel`

**Comment by kacollins** [comment]
Here's another type of message that could use some improvement:
`On Slack, avasond said: <@U2Y5YFWHX|avasond> set the channel purpose: Two-way communication with twitch.tv/techlahoma chat!`

**Comment by kacollins** [comment]
This is in progress!

**Comment by jackwkinsey** [comment]
It's weird that Slack thinks of these message types as "message". I know in the code that one of the checks for whether the message is sent to Twitch is if it is of type "message", you'd think Slack would treat these as some other message type. But I guess that'd be too easy :)
