### ISSUE TITLE
Create template config.js file

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/twitch_slack_bot#5]
Put a config.js file with placeholder strings in the repository so that people have the correct property names but not the actual keys.

**Comment by jackwkinsey** [comment]
I'll get this in. Should take long.

**Comment by jackwkinsey** [comment]
Done. Submitted PR. Will close once the PR is accepted.

**Comment by jackwkinsey** [comment]
Went ahead and just approved the PR since it was a small documentation change.
